### ISSUE TITLE
Missing OpenSSL in the docker image; unable to start

### ISSUE THREAD

**Issue by openface** [Huskehhh/dayz-monitor#5]
Hitting this error when trying to start the docker container. (jordynnewnham/dayz-monitor:latest)

```
dayz-monitor_1  | ./dayz-monitor: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

The image seems to be missing OpenSSL.

**Comment by openface** [comment]
Update: So I went into the running container, installed openssl via apt-get, and tried running `dayz-monitor` manually and am hitting this:

```
Error when updating cache: error sending request for url (https://api.battlemetrics.com/servers/10898108): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate)
```

**Comment by openface** [comment]
`apt-get install ca-certificates` did the trick.  So.. you're missing 2 packages. :D

**Comment by Huskehhh** [comment]
Cheers mate. Will fix ASAP 😀

**Comment by Huskehhh** [comment]
Should be resolved in the above commit.
Thanks again!
