### ISSUE TITLE
Halts on an error; does not continue

### ISSUE THREAD

**Issue by openface** [Huskehhh/dayz-monitor#6]
It seems that when it receives an error parsing a response from battlemetrics, the monitoring halts, and requires a manual restart.

```
dayz-monitor_1  | Error when updating cache: error decoding response body: expected value at line 1 column 1
```

or

```
dayz-monitor_1  | Error when updating cache: 500: Internal Server Error
```

Ideally the monitor should skip on a failed parse, and continue to try again.

**Comment by Huskehhh** [comment]
This should be fixed via the above commit
