### ISSUE TITLE
dynamic IP (BATTLEMETRICS_SEARCH)

### ISSUE THREAD

**Issue by Tesch1933** [Huskehhh/dayz-monitor#7]
Hi.  First of all, a big thank you for your second variant (BATTLEMETRICS_SEARCH).  I have now tested the variant for more than a month.  At some point there is always a problem.  The following message appears in the terminal after two days at the latest:

...

Updating channel to: 'player-count: 10'
Updating channel to: 'player-count: 10'
Updating channel to: 'player-count: 10'
thread '<unnamed>' panicked at 'BATTLEMETRICS_SERVER_ID environment variable not found!: NotPresent', src\main.rs:184:14
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
error: process didn't exit successfully: target\release\dayz_time_rs.exe (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)

After this message the error persists and the boots does not continue to work.  A restart fixes the problem.  Do you have any idea why this could be?

**Comment by Huskehhh** [comment]
Hey man! Sorry for the delayed response on this!

I can't think of a reason why the environment becomes stale over time, not including the environment variable... If you could ``git pull`` and ``cargo build --release`` and try with the latest code. That would be great.

If you are still having the issue, please feel free to re-open!

**Comment by Huskehhh** [comment]
REF https://github.com/Huskehhh/dayz-monitor/commit/69e1ee190ab68a2013c186402e99a9f99af36ae3
