### ISSUE TITLE
DISCORD_TOKEN NotPresent

### ISSUE THREAD

**Issue by PumpkinEater0069** [Huskehhh/dayz-monitor#9]
Hey there.
Unfortunately i am having issues to get the Bot running.

It always gets stuck with the discord bot token.

is there any special name i need to give my .env file or what else could be the issue?
![monitor error](https://user-images.githubusercontent.com/111933940/221383906-066fa56d-691f-45c2-8259-6a3f6a123454.png)

**Comment by Huskehhh** [comment]
Hi,

Your `.env` file should contain
```
DISCORD_TOKEN=paste-token-here
```

**Comment by PumpkinEater0069** [comment]
Well... that's what i did and i am confused about.

I tried to follow your guide but it doesn't work for me

**Comment by Huskehhh** [comment]
Ensure that the `.env` file is in the same directory that you are running `cargo run --release`, alternatively, run the command like so:

```
DISCORD_TOKEN=paste-token-here cargo run release
```
